services:
  - type: web
    name: edhremixer
    runtime: python
    plan: free
    buildCommand: |
      # Install Python dependencies
      cd api && pip install -r requirements.txt
      # Install Node and build Angular app
      cd ../frontend && npm install && npm run build
    startCommand: cd api && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PORT
        value: 10000
